version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:37"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "04:37"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
